import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ["'Prompt'", "sans-serif"],
        body: ["'Prompt'", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // SignMate Landing Page Colors
        "sq-pink": "#FF4D8D",
        "sq-yellow": "#FFD369",
        "sq-cream": "#F9F4EA",
        "sq-black": "#1A1A1A",
        "sq-dark-pink": "#E03D7A",
        "sq-dark-yellow": "#E6BC5F",
        // ── Material Design 3 tokens (Sign Master Memory mockup) ──
        "outline-variant": "#bab9b2",
        "inverse-surface": "#0e0f0a",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#eac25a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#f9d066",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#310b00",
        "surface-container": "#f5f4eb",
        "tertiary": "#b13e00",
        "on-tertiary-container": "#5a1c00",
        "tertiary-container": "#ff956a",
        "tertiary-dim": "#9d3600",
        "on-surface-variant": "#65655f",
        "primary-container": "#ff709d",
        "inverse-on-surface": "#9e9d96",
        "inverse-primary": "#fe4c8c",
        "on-surface": "#383833",
        "surface-bright": "#fefcf4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c4600",
        "tertiary-fixed": "#ff956a",
        "primary-fixed-dim": "#ff528f",
        "primary-dim": "#af0054",
        "on-tertiary-fixed-variant": "#692200",
        "on-primary-fixed-variant": "#5e002a",
        "on-background": "#383833",
        "error-container": "#fb5151",
        "secondary-dim": "#6f5500",
        "on-primary-fixed": "#000000",
        "surface-container-high": "#efeee5",
        "primary-fixed": "#ff709d",
        "on-secondary-fixed-variant": "#684f00",
        "secondary-container": "#f9d066",
        "surface": "#fefcf4",
        "surface-dim": "#e4e3d8",
        "tertiary-fixed-dim": "#ff7e48",
        "surface-container-highest": "#e9e9de",
        "on-error-container": "#570008",
        "on-secondary-fixed": "#453400",
        "surface-container-low": "#fbf9f1",
        "on-primary-container": "#4c0021",
        "surface-variant": "#e9e9de",
        "surface-tint": "#c11660",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      borderWidth: {
        '3': '3px',
        '4': '4px',
        '6': '6px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "bounce-in": {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "modal-in": {
          from: { opacity: "0", transform: "scale(0.95) translateY(10px)" },
          to: { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        "modal-out": {
          from: { opacity: "1", transform: "scale(1) translateY(0)" },
          to: { opacity: "0", transform: "scale(0.95) translateY(10px)" },
        },
        "backdrop-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "backdrop-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "bounce-in": "bounce-in 0.4s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-in-up": "fade-in-up 0.4s ease-out",
        "modal-in": "modal-in 0.3s ease-out",
        "modal-out": "modal-out 0.25s ease-in forwards",
        "backdrop-in": "backdrop-in 0.2s ease-out",
        "backdrop-out": "backdrop-out 0.25s ease-in forwards",
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px hsl(0 0% 0%)",
        "brutal-lg": "6px 6px 0px 0px hsl(0 0% 0%)",
        "brutal-sm": "2px 2px 0px 0px hsl(0 0% 0%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
